# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import skyquery
from skyquery.api.jobs_api import JobsApi  # noqa: E501
from skyquery.rest import ApiException


class TestJobsApi(unittest.TestCase):
    """JobsApi unit test stubs"""

    def setUp(self):
        self.api = skyquery.api.jobs_api.JobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_job(self):
        """Test case for cancel_job

        Cancels a single job.  # noqa: E501
        """
        pass

    def test_get_job(self):
        """Test case for get_job

        Returns a single job.  # noqa: E501
        """
        pass

    def test_get_queue(self):
        """Test case for get_queue

        Returns information about a job queue.  # noqa: E501
        """
        pass

    def test_list_jobs(self):
        """Test case for list_jobs

        Lists the jobs in the queue in descending order by submission time. Only jobs of the authenticated user are listed.  # noqa: E501
        """
        pass

    def test_list_queues(self):
        """Test case for list_queues

        Returns a list of all available job queues.  # noqa: E501
        """
        pass

    def test_submit_job(self):
        """Test case for submit_job

        Submits a new job of any kind.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
