# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import skyquery
from skyquery.models.column_list_response import ColumnListResponse  # noqa: E501
from skyquery.rest import ApiException


class TestColumnListResponse(unittest.TestCase):
    """ColumnListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testColumnListResponse(self):
        """Test ColumnListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyquery.models.column_list_response.ColumnListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
