# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import skyquery
from skyquery.models.column import Column  # noqa: E501
from skyquery.rest import ApiException


class TestColumn(unittest.TestCase):
    """Column unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testColumn(self):
        """Test Column"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyquery.models.column.Column()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
