# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import skyquery
from skyquery import Configuration
from skyquery.sciserver_client import SciServerClient
from skyquery.api.auth_api import AuthApi  # noqa: E501
from skyquery.rest import ApiException


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.configuration = Configuration()
        self.configuration.host = "http://localhost/dobos/skyquery-v1.4/Api/"
        self.configuration.proxy = 'http://localhost:8888'
        self.ssclient = SciServerClient(configuration=self.configuration)
        self.auth = skyquery.api.auth_api.AuthApi(self.ssclient)

    def tearDown(self):
        pass

    def test_authenticate(self):
        """Test case for authenticate

        Authenticates a user based on the submitted credentials.  # noqa: E501
        """
        self.auth.authenticate({"auth": {"username": "test", "password": "almafa"}})

    def test_authenticate_streaming(self):
        """Test case for authenticate

        Authenticates a user based on the submitted credentials.  # noqa: E501
        """
        self.auth.authenticate({"auth": {"username": "test", "password": "almafa"}}, _preload_content=False)

    def test_find_user_groups(self):
        """Test case for find_user_groups

          # noqa: E501
        """
        pass

    def test_get_current_user(self):
        """Test case for get_current_user

        Returns information on the authenticated user.  # noqa: E501
        """
        pass

    def test_get_current_user_role_in_group(self):
        """Test case for get_current_user_role_in_group

        Returns information on group membership.  # noqa: E501
        """
        pass

    def test_get_current_user_roles(self):
        """Test case for get_current_user_roles

        Returns information on group membership.  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

          # noqa: E501
        """
        pass

    def test_get_user_group(self):
        """Test case for get_user_group

          # noqa: E501
        """
        pass

    def test_get_user_group_members(self):
        """Test case for get_user_group_members

          # noqa: E501
        """
        pass

    def test_get_user_role_in_group(self):
        """Test case for get_user_role_in_group

        Returns information on group membership.  # noqa: E501
        """
        pass

    def test_get_user_roles(self):
        """Test case for get_user_roles

          # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
