# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import skyquery
from skyquery.models.headers import Headers  # noqa: E501
from skyquery.rest import ApiException


class TestHeaders(unittest.TestCase):
    """Headers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHeaders(self):
        """Test Headers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyquery.models.headers.Headers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
