# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import skyquery
from skyquery import Configuration
from skyquery.sciserver_client import SciServerClient
from skyquery.api.schema_api import SchemaApi  # noqa: E501
from skyquery.rest import ApiException
from skyquery.models import *

class TestSchemaApi(unittest.TestCase):
    """SchemaApi unit test stubs"""

    def setUp(self):
        self.configuration = Configuration()
        self.configuration.host = "http://localhost/dobos/skyquery-v1.4/Api/"
        self.configuration.proxy = 'http://localhost:8888'
        self.ssclient = SciServerClient(configuration=self.configuration)
        self.api = skyquery.api.schema_api.SchemaApi(self.ssclient)  # noqa: E501

    def tearDown(self):
        pass

    def test_get_dataset(self):
        """Test case for get_dataset

        Returns information about a single dataset  # noqa: E501
        """
        pass

    def test_get_table(self):
        """Test case for get_table

        Returns information about a single table.  # noqa: E501
        """
        pass

    def test_get_view(self):
        """Test case for get_view

        Returns information about a single view.  # noqa: E501
        """
        pass

    def test_list_datasets(self):
        """Test case for list_datasets

        Returns a list of all available datasets.  # noqa: E501
        """
        pass

    def test_list_table_columns(self):
        """Test case for list_table_columns

        Returns the list of columns of a table  # noqa: E501
        """
        pass

    def test_list_tables(self):
        """Test case for list_tables

        Returns a list of the tables of a dataset.  # noqa: E501
        """
        pass

    def test_list_view_columns(self):
        """Test case for list_view_columns

        Returns the list of columns of a view  # noqa: E501
        """
        pass

    def test_list_views(self):
        """Test case for list_views

        Returns a list of the views of a dataset.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
