# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import skyquery
from skyquery.models.user_group_list_response import UserGroupListResponse  # noqa: E501
from skyquery.rest import ApiException


class TestUserGroupListResponse(unittest.TestCase):
    """UserGroupListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserGroupListResponse(self):
        """Test UserGroupListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyquery.models.user_group_list_response.UserGroupListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
