# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import skyquery
from skyquery.models.view_list_response import ViewListResponse  # noqa: E501
from skyquery.rest import ApiException


class TestViewListResponse(unittest.TestCase):
    """ViewListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testViewListResponse(self):
        """Test ViewListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyquery.models.view_list_response.ViewListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
