# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import skyquery
from skyquery.models.auth_request import AuthRequest  # noqa: E501
from skyquery.rest import ApiException


class TestAuthRequest(unittest.TestCase):
    """AuthRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthRequest(self):
        """Test AuthRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyquery.models.auth_request.AuthRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
