# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import skyquery
from skyquery.models.job_dependency import JobDependency  # noqa: E501
from skyquery.rest import ApiException


class TestJobDependency(unittest.TestCase):
    """JobDependency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobDependency(self):
        """Test JobDependency"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyquery.models.job_dependency.JobDependency()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
