# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import skyquery
from skyquery import Configuration
from skyquery.sciserver_client import SciServerClient
from skyquery.api.data_api import DataApi  # noqa: E501
from skyquery.rest import ApiException


class TestDataApi(unittest.TestCase):
    """DataApi unit test stubs"""

    def setUp(self):
        self.configuration = Configuration()
        self.configuration.host = "http://localhost/dobos/skyquery-v1.4/Api/"
        self.configuration.proxy = 'http://localhost:8888'
        self.ssclient = SciServerClient(configuration=self.configuration)
        self.auth = skyquery.api.auth_api.AuthApi(self.ssclient)
        self.auth.authenticate({"auth": {"username": "test", "password": "almafa"}})
        self.api = skyquery.api.data_api.DataApi(self.ssclient)

    def tearDown(self):
        pass

    def test_download_table(self):
        """Test case for download_table

        Downloads a table in any supported data format.  # noqa: E501
        """
        res = self.api.download_table("MYDB", "MyCatalog", accept="text/csv", _preload_content=False)
        self.assertEqual(res, "0")

    def test_drop_table(self):
        """Test case for drop_table

        Drops a table from the user database.  # noqa: E501
        """
        pass

    def test_upload_table(self):
        """Test case for upload_table

        Uploads a table to a user database.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
