# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import skyquery
from skyquery.models.table import Table  # noqa: E501
from skyquery.rest import ApiException


class TestTable(unittest.TestCase):
    """Table unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTable(self):
        """Test Table"""
        # FIXME: construct object with mandatory attributes with example values
        # model = skyquery.models.table.Table()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
