# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from skyquery.api_client import ApiClient


class DataApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def download_table(self, dataset_name, table_name, **kwargs):  # noqa: E501
        """Downloads a table in any supported data format.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.download_table(dataset_name, table_name, async=True)
        >>> result = thread.get()

        :param async bool
        :param str dataset_name: null (required)
        :param str table_name: null (required)
        :param str top: null
        :return: file
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.download_table_with_http_info(dataset_name, table_name, **kwargs)  # noqa: E501
        else:
            (data) = self.download_table_with_http_info(dataset_name, table_name, **kwargs)  # noqa: E501
            return data

    def download_table_with_http_info(self, dataset_name, table_name, **kwargs):  # noqa: E501
        """Downloads a table in any supported data format.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.download_table_with_http_info(dataset_name, table_name, async=True)
        >>> result = thread.get()

        :param async bool
        :param str dataset_name: null (required)
        :param str table_name: null (required)
        :param str top: null
        :return: file
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['dataset_name', 'table_name', 'top']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method download_table" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'dataset_name' is set
        if ('dataset_name' not in params or
                params['dataset_name'] is None):
            raise ValueError("Missing the required parameter `dataset_name` when calling `download_table`")  # noqa: E501
        # verify the required parameter 'table_name' is set
        if ('table_name' not in params or
                params['table_name'] is None):
            raise ValueError("Missing the required parameter `table_name` when calling `download_table`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'dataset_name' in params:
            path_params['datasetName'] = params['dataset_name']  # noqa: E501
        if 'table_name' in params:
            path_params['tableName'] = params['table_name']  # noqa: E501

        query_params = []
        if 'top' in params:
            query_params.append(('top', params['top']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            'V1/Data.svc/{datasetName}/{tableName}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='file',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def drop_table(self, dataset_name, table_name, **kwargs):  # noqa: E501
        """Drops a table from the user database.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.drop_table(dataset_name, table_name, async=True)
        >>> result = thread.get()

        :param async bool
        :param str dataset_name: null (required)
        :param str table_name: null (required)
        :return: RestError
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.drop_table_with_http_info(dataset_name, table_name, **kwargs)  # noqa: E501
        else:
            (data) = self.drop_table_with_http_info(dataset_name, table_name, **kwargs)  # noqa: E501
            return data

    def drop_table_with_http_info(self, dataset_name, table_name, **kwargs):  # noqa: E501
        """Drops a table from the user database.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.drop_table_with_http_info(dataset_name, table_name, async=True)
        >>> result = thread.get()

        :param async bool
        :param str dataset_name: null (required)
        :param str table_name: null (required)
        :return: RestError
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['dataset_name', 'table_name']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method drop_table" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'dataset_name' is set
        if ('dataset_name' not in params or
                params['dataset_name'] is None):
            raise ValueError("Missing the required parameter `dataset_name` when calling `drop_table`")  # noqa: E501
        # verify the required parameter 'table_name' is set
        if ('table_name' not in params or
                params['table_name'] is None):
            raise ValueError("Missing the required parameter `table_name` when calling `drop_table`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'dataset_name' in params:
            path_params['datasetName'] = params['dataset_name']  # noqa: E501
        if 'table_name' in params:
            path_params['tableName'] = params['table_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            'V1/Data.svc/{datasetName}/{tableName}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='RestError',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def upload_table(self, dataset_name, table_name, data, **kwargs):  # noqa: E501
        """Uploads a table to a user database.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.upload_table(dataset_name, table_name, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str dataset_name: null (required)
        :param str table_name: null (required)
        :param file data: null (required)
        :return: RestError
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.upload_table_with_http_info(dataset_name, table_name, data, **kwargs)  # noqa: E501
        else:
            (data) = self.upload_table_with_http_info(dataset_name, table_name, data, **kwargs)  # noqa: E501
            return data

    def upload_table_with_http_info(self, dataset_name, table_name, data, **kwargs):  # noqa: E501
        """Uploads a table to a user database.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.upload_table_with_http_info(dataset_name, table_name, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str dataset_name: null (required)
        :param str table_name: null (required)
        :param file data: null (required)
        :return: RestError
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['dataset_name', 'table_name', 'data']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method upload_table" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'dataset_name' is set
        if ('dataset_name' not in params or
                params['dataset_name'] is None):
            raise ValueError("Missing the required parameter `dataset_name` when calling `upload_table`")  # noqa: E501
        # verify the required parameter 'table_name' is set
        if ('table_name' not in params or
                params['table_name'] is None):
            raise ValueError("Missing the required parameter `table_name` when calling `upload_table`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `upload_table`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'dataset_name' in params:
            path_params['datasetName'] = params['dataset_name']  # noqa: E501
        if 'table_name' in params:
            path_params['tableName'] = params['table_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            'V1/Data.svc/{datasetName}/{tableName}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='RestError',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
