# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from skyquery.models.headers import Headers  # noqa: F401,E501


class Credentials(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'username': 'str',
        'password': 'str',
        'headers': 'Headers'
    }

    attribute_map = {
        'username': 'username',
        'password': 'password',
        'headers': 'headers'
    }

    def __init__(self, username=None, password=None, headers=None):  # noqa: E501
        """Credentials - a model defined in Swagger"""  # noqa: E501

        self._username = None
        self._password = None
        self._headers = None
        self.discriminator = None

        if username is not None:
            self.username = username
        if password is not None:
            self.password = password
        if headers is not None:
            self.headers = headers

    @property
    def username(self):
        """Gets the username of this Credentials.  # noqa: E501


        :return: The username of this Credentials.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this Credentials.


        :param username: The username of this Credentials.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def password(self):
        """Gets the password of this Credentials.  # noqa: E501


        :return: The password of this Credentials.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this Credentials.


        :param password: The password of this Credentials.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def headers(self):
        """Gets the headers of this Credentials.  # noqa: E501


        :return: The headers of this Credentials.  # noqa: E501
        :rtype: Headers
        """
        return self._headers

    @headers.setter
    def headers(self, headers):
        """Sets the headers of this Credentials.


        :param headers: The headers of this Credentials.  # noqa: E501
        :type: Headers
        """

        self._headers = headers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Credentials):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
