# coding: utf-8

"""
    null

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: null
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class JobDependency(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'predecessor_job': 'str',
        'condition': 'str'
    }

    attribute_map = {
        'predecessor_job': 'predecessorJob',
        'condition': 'condition'
    }

    def __init__(self, predecessor_job=None, condition=None):  # noqa: E501
        """JobDependency - a model defined in Swagger"""  # noqa: E501

        self._predecessor_job = None
        self._condition = None
        self.discriminator = None

        if predecessor_job is not None:
            self.predecessor_job = predecessor_job
        if condition is not None:
            self.condition = condition

    @property
    def predecessor_job(self):
        """Gets the predecessor_job of this JobDependency.  # noqa: E501


        :return: The predecessor_job of this JobDependency.  # noqa: E501
        :rtype: str
        """
        return self._predecessor_job

    @predecessor_job.setter
    def predecessor_job(self, predecessor_job):
        """Sets the predecessor_job of this JobDependency.


        :param predecessor_job: The predecessor_job of this JobDependency.  # noqa: E501
        :type: str
        """

        self._predecessor_job = predecessor_job

    @property
    def condition(self):
        """Gets the condition of this JobDependency.  # noqa: E501


        :return: The condition of this JobDependency.  # noqa: E501
        :rtype: str
        """
        return self._condition

    @condition.setter
    def condition(self, condition):
        """Sets the condition of this JobDependency.


        :param condition: The condition of this JobDependency.  # noqa: E501
        :type: str
        """

        self._condition = condition

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobDependency):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
